### ISSUE TITLE
TypeError: failed to fetch #2

### ISSUE THREAD

**Issue by MotorTruck1221** [titaniumnetwork-dev/Ultraviolet-App#6]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

**I know this is an issue that has already been opened. This is more detailed, however**

## Expected Behavior

* When going to any website (e.x: https://github.com) it should show the website that the user has requested

## Current Behavior

* When I Type in a url it throws an error of: `TypeError: failed to fetch` pictures below in order (Ungoogle Chromium v106)
![image](https://user-images.githubusercontent.com/73721704/193987070-4953666d-fe2f-4c2c-a28b-f6bd6747b590.png)
![image](https://user-images.githubusercontent.com/73721704/193987008-947ab137-260f-4280-a028-160f0526d6fb.png)
![image](https://user-images.githubusercontent.com/73721704/193987136-26d5a162-5bc3-4b94-a645-07ebb2e5656c.png)

## Possible Solution

* I believe this is more related to the [Ultraviolet Static](https://github.com/titaniumnetwork-development/ultraviolet-static) Repository as one version ago this was working fine.

## Steps to Reproduce

1. Setup the newest version of Ultraviolet-Node
2. Type in (or search) what ever you wish 
3. See a `TypeError: failed to fetch`

## Context (Environment)

* Host: Hosted on Digital ocean VPS. 
* OS: Ubuntu 20.04 (LTS)
* My setup: NGINX Proxy Manager --> Ultraviolet
* Node JS version: 18
* NPM version 8
* I am passing all correct headers:
```nginx
location / { 
                # Upgrade WebSockets
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'Upgrade';
                # Increase header buffer
                proxy_connect_timeout 10; 
                proxy_send_timeout 90; 
                proxy_read_timeout 90; 
                proxy_buffer_size 128k;
                proxy_buffers 4 256k;
                proxy_busy_buffers_size 256k;
                proxy_temp_file_write_size 256k;
                proxy_pass http://10.124.0.3:1042; # change this to the port UltraViolet is listening on

            # The small block below will block googlebot
            if ($http_user_agent ~ (Googlebot)) {
                return 403;
            }
        }
```
(See [Proxdocs](https://github.com/degen-dev/proxdocs))
* Tried on three different browsers:
* Firefox v105.0.2
* Ungoogled Chromium v106.0.5249.9
* Chrome v106.0.5249.91

* I am trying to update my UltraViolet instance hosted on my VPS and it will break if I do.
* I am a developer for a non-official proxy called [Weeb Central](https://github.com/weeb-network/wc) and updating the website will **break** it
* I am developing my own proxy (not public on GH yet) and updating will break the website from working

## Possible Implementation
I don't know a possible fix however I hope this is detailed enough that it will help it get fixed sooner.

**Comment by e9x** [comment]
A cause of this error may be due to problems with the underlying Bare Server.

Here are steps to debug this problem:
- Go to the Ultraviolet-Node homepage
- Open Devtools
- Go to the network tab
- Enable "Persist Logs"
- Produce your problem
- Look for a request to `/bare/v1/`, what's the status code?

Can you provide a screenshot of `/bare/`?

**Comment by nevr13** [comment]
This also happens to me, not sure how to fix it. This wasn't doing this previously, and I hadn't updated the app at all.

**Comment by MemeGiver** [comment]
same issue here, however spamming the reload button partially fixes it with https://incog.dev/bare/v1/ responding with "MISSING_BARE_HEADER"
nodejs v18 & npm 8

![image](https://user-images.githubusercontent.com/109994818/196015150-1b23e770-d328-48bb-a3dd-a9233f31aa6c.png)

**Comment by e9x** [comment]
Ah. Not only are we using an external Bare server by default (this was a mistake...) but incog.dev's bare server has fallen. Every other request on my end goes through. This will be addressed shortly.

**Comment by e9x** [comment]
This should be fixed. Redeploy your instance.

**Comment by MemeGiver** [comment]
> This should be fixed. Redeploy your instance.

still happening after cloning this repo with the latest commit
incog.dev is also reporting the same error

![image](https://user-images.githubusercontent.com/109994818/196015943-bc507468-b72d-4c02-81d7-23e515c9de9e.png)

**Comment by e9x** [comment]
> > This should be fixed. Redeploy your instance.
> 
> still happening after cloning this repo with the latest commit incog.dev is also reporting the same error
> 
> ![image](https://user-images.githubusercontent.com/109994818/196015943-bc507468-b72d-4c02-81d7-23e515c9de9e.png)

I just fixed several things to get this working. It should work now, try again.

**Comment by MemeGiver** [comment]
updated and issues are still present
![image](https://user-images.githubusercontent.com/109994818/196016173-e9e8a83e-b90e-4fa5-9fb7-f2cdb079a66a.png)

**Comment by e9x** [comment]
@MemeGiver Try clearing your site data. This will refresh the UV config.

**Comment by MemeGiver** [comment]
> @MemeGiver Try clearing your site data. This will refresh the UV config.

working now, thanks a lot
